# Generated by Django 2.1.5 on 2019-09-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190317_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
